name = "CPIDataBase"
uuid = "bc2aee9a-d1f8-4cce-8750-9c1afc923989"
version = "0.6.25"
authors = ["Rodrigo Chang and DIE-BG collaborators"]

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
AbstractTrees = ">= 0.3"
DataFrames = ">= 1"
PrettyTables = ">= 1"
Printf = ">=1.11"
Statistics = ">=1.11"
julia = ">= 1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
